export interface HotelFacilities {
    id: number;
    // created: Date;
    // lastUpdated: Date;

    restaurant: boolean;
    lift: boolean;
    wifi: boolean;
    conferenceRoom: boolean;
    swimmingPool: boolean;
    sportsZone: boolean;
    gym: boolean;
    spa: boolean;
    bar: boolean;
    helipad: boolean;
    // ac: boolean;
    frontDesk: boolean;
    roomService: boolean;
    electricity: boolean;
    security: boolean;
    complementaryBreakfast: boolean;
    coffeeShop: boolean;
    freeParking: boolean;
    airportTransportation: boolean;
    businessCenter: boolean;
    meetingRoom: boolean;
    doctorOnCall: boolean;
    wakeupService: boolean;
    wheelChairAccessible: boolean;
    safeDepositBox: boolean;
    nonSmokingRoom: boolean;
    vipFloor: boolean;
    // elevator: boolean;
    acceptCreditCard: boolean;
    newspaper: boolean;
    laundry: boolean;
    lobby: boolean;
    foreignExchange: boolean;
    executiveLaunge: boolean;
    babySitting: boolean;
    freeCancellation: boolean;
}
